import type { ForkBuildMeta } from "@/fork-info";

// AUTO-GENERATED by build-all-feats.yml at build time. Do not edit.
// CI overwrites this file with the real values; the committed defaults keep
// dev checkouts compiling.
export const FORK_BUILD_META: ForkBuildMeta = {
  version: null,
  builtAt: null,
  commit: null,
};
